# Generated by Django 5.1 on 2024-08-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txhash', models.CharField(max_length=66)),
                ('blockno', models.IntegerField()),
                ('unixtimestamp', models.IntegerField()),
                ('datetime_utc', models.DateTimeField()),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('contractaddress', models.CharField(blank=True, max_length=42, null=True)),
                ('value_in_eth', models.DecimalField(decimal_places=10, max_digits=20)),
                ('value_out_eth', models.DecimalField(decimal_places=10, max_digits=20)),
                ('current_value_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fee_eth', models.DecimalField(decimal_places=10, max_digits=20)),
                ('txnfee_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('historical_sprice_eth', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(max_length=10)),
                ('errcode', models.CharField(blank=True, max_length=10, null=True)),
                ('method', models.CharField(max_length=20)),
            ],
        ),
    ]
